Repository uber-workflow/probot-app-pr-label, pull requests merged in 2018-08, with the labels that each got.

#4 Update deploy documentation to include required permissions and events
  docs/deploy.md
Labels: docs

#5 Release v1.0.0
  package.json
Labels: release

#7 Release v1.0.1
  package.json
Labels: release

#8 Remove comments when missing label is resolved automatically
  __tests__/index.test.js
  index.js
Labels: feature

#9 Release v1.1.0
  package.json
Labels: release

#10 Replace error comments with status message
  index.js
Labels: enhancement, feature

#11 Release v1.2.0
  package.json
Labels: release

#12 Fix tests now that Buildkite is running
  .buildkite/pipeline.yml
  __tests__/index.test.js
  index.js
Labels: bugfix
